# templates/default/docker-compose.yml
version: '3.8'

x-app-environment: &app-environment
  APP_NAME: "{{PROJECT_NAME}}"
  APP_ENV: local
  APP_DEBUG: true
  APP_URL: "https://{{PROJECT_DOMAIN}}"
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: "${DB_DATABASE:-laravel}"
  DB_USERNAME: "${DB_USERNAME:-laravel}"
  DB_PASSWORD: "${DB_PASSWORD:-password}"
  REDIS_HOST: redis
  REDIS_PORT: 6379
  MAIL_MAILER: smtp
  MAIL_HOST: mailhog
  MAIL_PORT: 1025

networks:
  tacocraft:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  minio_data:

services:
  nginx:
    image: nginx:alpine
    container_name: {{PROJECT_NAME}}_nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - tacocraft

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION={{PHP_VERSION}}
    container_name: {{PROJECT_NAME}}_app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      <<: *app-environment
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
      - redis
    networks:
      - tacocraft

  mysql:
    image: mysql:8.0
    container_name: {{PROJECT_NAME}}_mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${DB_DATABASE:-laravel}"
      MYSQL_USER: "${DB_USERNAME:-laravel}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - tacocraft

  redis:
    image: redis:7-alpine
    container_name: {{PROJECT_NAME}}_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - tacocraft

  # Servicios opcionales basados en configuración...